# Generated by Django 4.0.3 on 2022-05-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('certification', models.IntegerField()),
            ],
            options={
                'db_table': 'authentication_numbers',
            },
        ),
        migrations.CreateModel(
            name='DrinkCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'drink_capacities',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'physicals',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'religions',
            },
        ),
        migrations.CreateModel(
            name='SoloReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'solo_reasons',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.URLField(max_length=400)),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=254, unique=True)),
                ('sendbird_id', models.CharField(blank=True, max_length=400)),
                ('customer_uid', models.CharField(blank=True, max_length=400)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('gender', models.SmallIntegerField(null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('birth_date', models.CharField(blank=True, max_length=20)),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reported_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=300)),
                ('kakao_id', models.CharField(blank=True, max_length=50)),
                ('kakao_nickname', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink_capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.drinkcapacity')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.job')),
                ('physical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.physical')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.religion')),
                ('solo_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.soloreason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('url', models.URLField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_images',
            },
        ),
    ]
